# Generated by Django 5.1.7 on 2025-03-26 07:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Translate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, verbose_name='Name of translate')),
                ('file_one', models.FileField(blank=True, upload_to='media', verbose_name='File from translate')),
                ('file_two', models.FileField(blank=True, upload_to='media', verbose_name='File to translate')),
                ('translate_from_text', models.TextField(blank=True, verbose_name='Translate from text')),
                ('translated_text', models.TextField(blank=True, verbose_name='Translated text')),
                ('author', models.ForeignKey(
                    null=True,
                    on_delete=django.db.models.deletion.CASCADE,
                    to=settings.AUTH_USER_MODEL,
                )),
            ],
        ),
    ]
