# Generated by Django 5.1.7 on 2025-03-26 10:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lang', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='translate',
            name='language_input',
            field=models.CharField(blank=True, max_length=4, verbose_name='Language input'),
        ),
        migrations.AddField(
            model_name='translate',
            name='language_output',
            field=models.CharField(blank=True, max_length=4, verbose_name='Language output'),
        ),
        migrations.AlterField(
            model_name='translate',
            name='author',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
