# Generated by Django 5.1.7 on 2025-03-26 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lang', '0003_alter_translate_author_alter_translate_file_one_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='translate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата перевода'),
        ),
    ]
